version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - broker

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - broker

  backend:
    build: .
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/keys/pafkiuq.json
      - FIRESTORE_PROJECT_ID=pafkiuq-62d96
    volumes:
      - ./.keys:/keys
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
    networks:
      - broker

networks:
  broker:
    driver: bridge
