version: "3"

services:
  redis:
    image: redis:7.0.4-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - broker

  backend:
    build: .
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/keys/chessvars-test.json
      - FIRESTORE_PROJECT_ID=chessvars-test
    volumes:
      - ./.keys:/keys
    depends_on:
      - redis
    ports:
      - 8080:8080
    networks:
      - broker

volumes:
  redis-data:
    driver: local

networks:
  broker:
    driver: bridge
