version: "3"

services:
  backend:
    build: .
    environment:
      - FIRESTORE_PROJECT_ID=chessvars-test
    ports:
      - 8080:8080
    networks:
      - broker

networks:
  broker:
    driver: bridge
