version: "3"

services:
  redis:
    image: redis:7.0.4-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - broker

  backend:
    build: .
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/keys/pafkiuq.json
      - FIRESTORE_PROJECT_ID=pafkiuq-62d96
    volumes:
      - ./.keys:/keys
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
    networks:
      - broker

volumes:
  redis-data:
    driver: local

networks:
  broker:
    driver: bridge
