name: deploy
on:
  push:
    branches:
      - main
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build and push docker
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: garlicgarrison/chessvars-backend:latest
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: ssh into aws ec2
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AWS_SSH_SECRET }}
          name: id
          known_hosts: ${{ secrets.AWS_SSH_PUBLIC_KEY }}
          config: |
            Host chessvars
              HostName ec2-18-234-125-199.compute-1.amazonaws.com
              User ec2-user
              IdentityFile ~/.ssh/id
      - name: ssh deploy
        run: |
          cd /home/runner/.ssh
          ls -a
          ssh chessvars info
